// API: 識別文本中最可能被判定為 AI 生成的句子，供修改與儲存
import type { NextApiRequest, NextApiResponse } from 'next';
import { callLLM } from '@/lib/ai';
import { deductCredits } from '@/lib/credits';

type ResBody = { sentences: string[]; error?: string };

export default async function handler(req: NextApiRequest, res: NextApiResponse<ResBody>) {
  res.setHeader('Content-Type', 'application/json');

  if (req.method !== 'POST') {
    return res.status(405).json({ sentences: [] });
  }

  const deduct = await deductCredits(req, res, 0);
  if (!deduct.ok) return;

  const { text } = (req.body ?? {}) as { text?: string };
  if (!text || typeof text !== 'string' || !text.trim()) {
    return res.status(400).json({ sentences: [] });
  }

  const trimmed = text.trim().slice(0, 4000);
  const isZh = /[\u4e00-\u9fff]/.test(trimmed);

  const systemPrompt = isZh
    ? `你是 AI 文本檢測專家。分析給定段落，找出 2-4 句「最可能被 GPTZero 等工具判定為 AI 生成」的句子。
這些句子通常特徵：過於流暢、套話、空洞形容詞、機械化結構。
輸出格式：每句一行，僅輸出原文句子，不要編號、不要解釋。若無明顯問題句，輸出空行。`
    : `You are an AI text detection expert. Analyze the paragraph and identify 2-4 sentences that are MOST likely to be flagged as AI-generated by tools like GPTZero.
These sentences often have: overly smooth flow, clichés, vague adjectives, mechanical structure.
Output format: One sentence per line, output ONLY the original sentences, no numbering or explanation. If no obvious problematic sentences, output a blank line.`;

  try {
    const result = await callLLM(
      [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: (isZh ? '分析以下段落：\n\n' : 'Analyze:\n\n') + trimmed },
      ],
      {
        model: process.env.OPENROUTER_GPT4O_MINI_MODEL ?? 'openai/gpt-4o-mini',
        temperature: 0.2,
        maxTokens: 500,
        timeoutMs: 20_000,
        title: 'AI Identify Sentences',
        referer: process.env.NEXT_PUBLIC_APP_URL,
      }
    );

    const lines = (result || '')
      .split(/\n/)
      .map((s) => s.replace(/^\d+[\.\)]\s*/, '').trim())
      .filter((s) => s.length > 15 && trimmed.includes(s));
    const sentences = [...new Set(lines)].slice(0, 5);

    return res.status(200).json({ sentences });
  } catch (err: any) {
    console.error('[ai-identify-sentences]', err?.message);
    return res.status(500).json({ sentences: [] });
  }
}
